### ISSUE TITLE
Saved model versions

### ISSUE THREAD

**Issue by d6y** [KavrakiLab/MetaTrans#1]
Hello - thanks for making this code and the models available.

I'm running into an issue during the `translate_molecules` step of the readme. I'm seeing:

```
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '[path omitted]python3.5/site-packages/torch/_utils.py'>
```

This suggests the saved models used a different version of (perhaps) pytorch.

However, I'm running miniconda (conda 4.8.5) and had to also `conda install -y ipython` to get the `prepare_input_file.py` step to run. So possibly it's more an environment issue here. 

A further possible clue: the conda set up didn't include comet_ml which is referenced in `translate.py`. But possibly it's not used?

If you have any thoughts on what I could try to get through the readme steps, that'd be much appreciated.

**Comment by EleniLitsa** [comment]
Thank you very much for bringing this issue to our attention. The Pytorch version should be 1.1.0 instead of 0.4.1. We have updated the README file.

**Comment by d6y** [comment]
Thank you - I can now load the models 👍
